title = "gitleaks config"

[extend]
useDefault = true

[allowlist]
    description = "Allowlisted files"
    paths = [
    '''megalinter-reports''',
    '''(.*?)gitleaks\.toml$''',
    '''(.*?)_test\.go$''',
    '''(?i)(.*?)(png|jpeg|jpg|gif|doc|docx|pdf|bin|xls|xlsx|pyc|zip)$''']
