---
name: Continuous Integration

"on":
    push:
        branches: [main]
    pull_request:
        branches: [main]

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

permissions:
    contents: read
    security-events: write
    actions: read
    pull-requests: read

jobs:
    ci:
        uses: arillso/.github/.github/workflows/ci-go-action.yml@2026-03-09

    security-secrets:
        uses: arillso/.github/.github/workflows/security-secrets.yml@2026-03-09
